// ============================================================================
// File:        MainForm.Designer.cs
// Project:     Aperture Science Cursor Relocation Suite (ASCRS)
// Author:      Daniel Yu
// Date:        2026-03-27
// Description:
//   This file is auto-generated by the Windows Forms designer. It contains
//   the partial class MainForm with the designer‑generated code that sets up
//   the form's properties and components. In this project, the form is
//   configured programmatically in MainForm.cs, so this file only contains
//   the minimal code required for the designer to function. It is kept for
//   compatibility and should not be manually edited.
// ============================================================================

namespace ASCRS.Forms
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            // This component is intentionally empty because all form
            // configuration (borderless, transparent, topmost, etc.) is
            // performed programmatically in the constructor of MainForm.cs.
            components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
        }
    }
}